# Generated by Django 3.0.4 on 2020-04-05 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adrs', models.TextField(blank=True, max_length=500, verbose_name='Address')),
                ('phon', models.BigIntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('lngd', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Longitude')),
                ('latd', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Latitude')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logb', models.BooleanField()),
                ('tlog', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
